### ISSUE TITLE
AttributeError: 'AutoGPTPMPlugin' object has no attribute 'cli_trello'

### ISSUE THREAD

**Issue by iT-Boyer** [minfenglu/AutoGPT-PM-Plugin#3]

**Comment by minfenglu** [comment]
Hi @iT-Boyer please follow the [README](https://github.com/minfenglu/AutoGPT-PM-Plugin/blob/main/src/autogpt_plugins/pm_plugins/trello_plugin/READNE.md) to create a Trello configuration file and set TRELLO_CONFIG_FILE to point to the config file location.

**Comment by iT-Boyer** [comment]
print this log on startup
```
 File "plugins/AutoGPT-PM-Plugin.zip/AutoGPT-PM-Plugin/src/autogpt_plugins/pm_plugins/trello_plugin/trello_plugin.py", line 236, in __init__
KeyError: 'NEXT'
```
 
my config in `.env`：
```
TRELLO_CONFIG_FILE=./trello.yaml
```
and Create a `trello.yaml` file in the `Auto-GPT/`directory 
```yaml
name: Trello Configurations
user_name:
  itboyer
board_name:
  周任务
board_lists:
  -
    name: TODO
    tag: backlog
  -
    name: WAIT
    tag: doing
  -
    name: DONE
    tag: done
idle_threshold:
  4320
supervisor_user_name:
  itboyer

```
